// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/proto/job_service.proto

package jobv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // job type: "email", "hello", etc.
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Options       *JobOptions            `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobRequest) Reset() {
	*x = SubmitJobRequest{}
	mi := &file_api_proto_job_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobRequest) ProtoMessage() {}

func (x *SubmitJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_job_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobRequest.ProtoReflect.Descriptor instead.
func (*SubmitJobRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_job_service_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitJobRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SubmitJobRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SubmitJobRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SubmitJobRequest) GetOptions() *JobOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type JobOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxRetry      int32                  `protobuf:"varint,1,opt,name=max_retry,json=maxRetry,proto3" json:"max_retry,omitempty"`                 // max retry attempts (default: 5)
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`                                        // queue name for priority (default: "default")
	RunAtUnixSec  int64                  `protobuf:"varint,3,opt,name=run_at_unix_sec,json=runAtUnixSec,proto3" json:"run_at_unix_sec,omitempty"` // optional: run at time (Unix seconds)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobOptions) Reset() {
	*x = JobOptions{}
	mi := &file_api_proto_job_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobOptions) ProtoMessage() {}

func (x *JobOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_job_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobOptions.ProtoReflect.Descriptor instead.
func (*JobOptions) Descriptor() ([]byte, []int) {
	return file_api_proto_job_service_proto_rawDescGZIP(), []int{1}
}

func (x *JobOptions) GetMaxRetry() int32 {
	if x != nil {
		return x.MaxRetry
	}
	return 0
}

func (x *JobOptions) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *JobOptions) GetRunAtUnixSec() int64 {
	if x != nil {
		return x.RunAtUnixSec
	}
	return 0
}

type SubmitJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitJobResponse) Reset() {
	*x = SubmitJobResponse{}
	mi := &file_api_proto_job_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitJobResponse) ProtoMessage() {}

func (x *SubmitJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_job_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitJobResponse.ProtoReflect.Descriptor instead.
func (*SubmitJobResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_job_service_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_api_proto_job_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_job_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_job_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "pending", "processing", "completed", "failed", "archived"
	Attempt       int32                  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	LastError     string                 `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusResponse) Reset() {
	*x = GetJobStatusResponse{}
	mi := &file_api_proto_job_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusResponse) ProtoMessage() {}

func (x *GetJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_job_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_job_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetJobStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetJobStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetJobStatusResponse) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *GetJobStatusResponse) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type ListArchivedJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`  // optional; if empty, list from all queues
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // max items to return (default 100)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArchivedJobsRequest) Reset() {
	*x = ListArchivedJobsRequest{}
	mi := &file_api_proto_job_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArchivedJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArchivedJobsRequest) ProtoMessage() {}

func (x *ListArchivedJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_job_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArchivedJobsRequest.ProtoReflect.Descriptor instead.
func (*ListArchivedJobsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_job_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListArchivedJobsRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *ListArchivedJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ArchivedJobInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Attempt       int32                  `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	LastError     string                 `protobuf:"bytes,6,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchivedJobInfo) Reset() {
	*x = ArchivedJobInfo{}
	mi := &file_api_proto_job_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchivedJobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchivedJobInfo) ProtoMessage() {}

func (x *ArchivedJobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_job_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchivedJobInfo.ProtoReflect.Descriptor instead.
func (*ArchivedJobInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_job_service_proto_rawDescGZIP(), []int{6}
}

func (x *ArchivedJobInfo) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ArchivedJobInfo) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *ArchivedJobInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ArchivedJobInfo) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ArchivedJobInfo) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ArchivedJobInfo) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type ListArchivedJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*ArchivedJobInfo     `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArchivedJobsResponse) Reset() {
	*x = ListArchivedJobsResponse{}
	mi := &file_api_proto_job_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArchivedJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArchivedJobsResponse) ProtoMessage() {}

func (x *ListArchivedJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_job_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArchivedJobsResponse.ProtoReflect.Descriptor instead.
func (*ListArchivedJobsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_job_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListArchivedJobsResponse) GetJobs() []*ArchivedJobInfo {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type RetryArchivedJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"` // required: queue where the archived task lives
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryArchivedJobRequest) Reset() {
	*x = RetryArchivedJobRequest{}
	mi := &file_api_proto_job_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryArchivedJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryArchivedJobRequest) ProtoMessage() {}

func (x *RetryArchivedJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_job_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryArchivedJobRequest.ProtoReflect.Descriptor instead.
func (*RetryArchivedJobRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_job_service_proto_rawDescGZIP(), []int{8}
}

func (x *RetryArchivedJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RetryArchivedJobRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

type RetryArchivedJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryArchivedJobResponse) Reset() {
	*x = RetryArchivedJobResponse{}
	mi := &file_api_proto_job_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryArchivedJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryArchivedJobResponse) ProtoMessage() {}

func (x *RetryArchivedJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_job_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryArchivedJobResponse.ProtoReflect.Descriptor instead.
func (*RetryArchivedJobResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_job_service_proto_rawDescGZIP(), []int{9}
}

type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`    // optional filter by queue
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`  // optional filter: pending, scheduled, processing, completed, failed, archived
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`   // max items (default 100)
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"` // pagination offset
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_api_proto_job_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_job_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_job_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListJobsRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *ListJobsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListJobsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type JobInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	JobId              string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Type               string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Queue              string                 `protobuf:"bytes,3,opt,name=queue,proto3" json:"queue,omitempty"`
	Status             string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Attempt            int32                  `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	LastError          string                 `protobuf:"bytes,6,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	CreatedAtUnixSec   int64                  `protobuf:"varint,7,opt,name=created_at_unix_sec,json=createdAtUnixSec,proto3" json:"created_at_unix_sec,omitempty"`
	UpdatedAtUnixSec   int64                  `protobuf:"varint,8,opt,name=updated_at_unix_sec,json=updatedAtUnixSec,proto3" json:"updated_at_unix_sec,omitempty"`
	CompletedAtUnixSec int64                  `protobuf:"varint,9,opt,name=completed_at_unix_sec,json=completedAtUnixSec,proto3" json:"completed_at_unix_sec,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *JobInfo) Reset() {
	*x = JobInfo{}
	mi := &file_api_proto_job_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobInfo) ProtoMessage() {}

func (x *JobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_job_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobInfo.ProtoReflect.Descriptor instead.
func (*JobInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_job_service_proto_rawDescGZIP(), []int{11}
}

func (x *JobInfo) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *JobInfo) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *JobInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobInfo) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *JobInfo) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *JobInfo) GetCreatedAtUnixSec() int64 {
	if x != nil {
		return x.CreatedAtUnixSec
	}
	return 0
}

func (x *JobInfo) GetUpdatedAtUnixSec() int64 {
	if x != nil {
		return x.UpdatedAtUnixSec
	}
	return 0
}

func (x *JobInfo) GetCompletedAtUnixSec() int64 {
	if x != nil {
		return x.CompletedAtUnixSec
	}
	return 0
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobInfo             `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_api_proto_job_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_job_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_job_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListJobsResponse) GetJobs() []*JobInfo {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"` // optional; if empty, search in default queues
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_api_proto_job_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_job_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_job_service_proto_rawDescGZIP(), []int{13}
}

func (x *CancelJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CancelJobRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

type CancelJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobResponse) Reset() {
	*x = CancelJobResponse{}
	mi := &file_api_proto_job_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobResponse) ProtoMessage() {}

func (x *CancelJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_job_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobResponse.ProtoReflect.Descriptor instead.
func (*CancelJobResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_job_service_proto_rawDescGZIP(), []int{14}
}

type ListQueuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueuesRequest) Reset() {
	*x = ListQueuesRequest{}
	mi := &file_api_proto_job_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueuesRequest) ProtoMessage() {}

func (x *ListQueuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_job_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueuesRequest.ProtoReflect.Descriptor instead.
func (*ListQueuesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_job_service_proto_rawDescGZIP(), []int{15}
}

type QueueInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pending       int64                  `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"`
	Active        int64                  `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	Scheduled     int64                  `protobuf:"varint,4,opt,name=scheduled,proto3" json:"scheduled,omitempty"`
	Retry         int64                  `protobuf:"varint,5,opt,name=retry,proto3" json:"retry,omitempty"`
	Archived      int64                  `protobuf:"varint,6,opt,name=archived,proto3" json:"archived,omitempty"`
	Paused        bool                   `protobuf:"varint,7,opt,name=paused,proto3" json:"paused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueInfo) Reset() {
	*x = QueueInfo{}
	mi := &file_api_proto_job_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueInfo) ProtoMessage() {}

func (x *QueueInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_job_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueInfo.ProtoReflect.Descriptor instead.
func (*QueueInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_job_service_proto_rawDescGZIP(), []int{16}
}

func (x *QueueInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueueInfo) GetPending() int64 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *QueueInfo) GetActive() int64 {
	if x != nil {
		return x.Active
	}
	return 0
}

func (x *QueueInfo) GetScheduled() int64 {
	if x != nil {
		return x.Scheduled
	}
	return 0
}

func (x *QueueInfo) GetRetry() int64 {
	if x != nil {
		return x.Retry
	}
	return 0
}

func (x *QueueInfo) GetArchived() int64 {
	if x != nil {
		return x.Archived
	}
	return 0
}

func (x *QueueInfo) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

type ListQueuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queues        []*QueueInfo           `protobuf:"bytes,1,rep,name=queues,proto3" json:"queues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueuesResponse) Reset() {
	*x = ListQueuesResponse{}
	mi := &file_api_proto_job_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueuesResponse) ProtoMessage() {}

func (x *ListQueuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_job_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueuesResponse.ProtoReflect.Descriptor instead.
func (*ListQueuesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_job_service_proto_rawDescGZIP(), []int{17}
}

func (x *ListQueuesResponse) GetQueues() []*QueueInfo {
	if x != nil {
		return x.Queues
	}
	return nil
}

type PauseQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseQueueRequest) Reset() {
	*x = PauseQueueRequest{}
	mi := &file_api_proto_job_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseQueueRequest) ProtoMessage() {}

func (x *PauseQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_job_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseQueueRequest.ProtoReflect.Descriptor instead.
func (*PauseQueueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_job_service_proto_rawDescGZIP(), []int{18}
}

func (x *PauseQueueRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

type PauseQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseQueueResponse) Reset() {
	*x = PauseQueueResponse{}
	mi := &file_api_proto_job_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseQueueResponse) ProtoMessage() {}

func (x *PauseQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_job_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseQueueResponse.ProtoReflect.Descriptor instead.
func (*PauseQueueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_job_service_proto_rawDescGZIP(), []int{19}
}

type UnpauseQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpauseQueueRequest) Reset() {
	*x = UnpauseQueueRequest{}
	mi := &file_api_proto_job_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpauseQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpauseQueueRequest) ProtoMessage() {}

func (x *UnpauseQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_job_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpauseQueueRequest.ProtoReflect.Descriptor instead.
func (*UnpauseQueueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_job_service_proto_rawDescGZIP(), []int{20}
}

func (x *UnpauseQueueRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

type UnpauseQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpauseQueueResponse) Reset() {
	*x = UnpauseQueueResponse{}
	mi := &file_api_proto_job_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpauseQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpauseQueueResponse) ProtoMessage() {}

func (x *UnpauseQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_job_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpauseQueueResponse.ProtoReflect.Descriptor instead.
func (*UnpauseQueueResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_job_service_proto_rawDescGZIP(), []int{21}
}

var File_api_proto_job_service_proto protoreflect.FileDescriptor

const file_api_proto_job_service_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/job_service.proto\x12\x06job.v1\"\x8b\x01\n" +
	"\x10SubmitJobRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12,\n" +
	"\aoptions\x18\x04 \x01(\v2\x12.job.v1.JobOptionsR\aoptions\"f\n" +
	"\n" +
	"JobOptions\x12\x1b\n" +
	"\tmax_retry\x18\x01 \x01(\x05R\bmaxRetry\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12%\n" +
	"\x0frun_at_unix_sec\x18\x03 \x01(\x03R\frunAtUnixSec\"*\n" +
	"\x11SubmitJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\",\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"~\n" +
	"\x14GetJobStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x05R\aattempt\x12\x1d\n" +
	"\n" +
	"last_error\x18\x04 \x01(\tR\tlastError\"E\n" +
	"\x17ListArchivedJobsRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\xa5\x01\n" +
	"\x0fArchivedJobInfo\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\x05R\aattempt\x12\x1d\n" +
	"\n" +
	"last_error\x18\x06 \x01(\tR\tlastError\"G\n" +
	"\x18ListArchivedJobsResponse\x12+\n" +
	"\x04jobs\x18\x01 \x03(\v2\x17.job.v1.ArchivedJobInfoR\x04jobs\"F\n" +
	"\x17RetryArchivedJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\"\x1a\n" +
	"\x18RetryArchivedJobResponse\"m\n" +
	"\x0fListJobsRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\xac\x02\n" +
	"\aJobInfo\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05queue\x18\x03 \x01(\tR\x05queue\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\x05R\aattempt\x12\x1d\n" +
	"\n" +
	"last_error\x18\x06 \x01(\tR\tlastError\x12-\n" +
	"\x13created_at_unix_sec\x18\a \x01(\x03R\x10createdAtUnixSec\x12-\n" +
	"\x13updated_at_unix_sec\x18\b \x01(\x03R\x10updatedAtUnixSec\x121\n" +
	"\x15completed_at_unix_sec\x18\t \x01(\x03R\x12completedAtUnixSec\"7\n" +
	"\x10ListJobsResponse\x12#\n" +
	"\x04jobs\x18\x01 \x03(\v2\x0f.job.v1.JobInfoR\x04jobs\"?\n" +
	"\x10CancelJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\"\x13\n" +
	"\x11CancelJobResponse\"\x13\n" +
	"\x11ListQueuesRequest\"\xb9\x01\n" +
	"\tQueueInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\apending\x18\x02 \x01(\x03R\apending\x12\x16\n" +
	"\x06active\x18\x03 \x01(\x03R\x06active\x12\x1c\n" +
	"\tscheduled\x18\x04 \x01(\x03R\tscheduled\x12\x14\n" +
	"\x05retry\x18\x05 \x01(\x03R\x05retry\x12\x1a\n" +
	"\barchived\x18\x06 \x01(\x03R\barchived\x12\x16\n" +
	"\x06paused\x18\a \x01(\bR\x06paused\"?\n" +
	"\x12ListQueuesResponse\x12)\n" +
	"\x06queues\x18\x01 \x03(\v2\x11.job.v1.QueueInfoR\x06queues\")\n" +
	"\x11PauseQueueRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\"\x14\n" +
	"\x12PauseQueueResponse\"+\n" +
	"\x13UnpauseQueueRequest\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\"\x16\n" +
	"\x14UnpauseQueueResponse2\x9d\x05\n" +
	"\n" +
	"JobService\x12@\n" +
	"\tSubmitJob\x12\x18.job.v1.SubmitJobRequest\x1a\x19.job.v1.SubmitJobResponse\x12I\n" +
	"\fGetJobStatus\x12\x1b.job.v1.GetJobStatusRequest\x1a\x1c.job.v1.GetJobStatusResponse\x12=\n" +
	"\bListJobs\x12\x17.job.v1.ListJobsRequest\x1a\x18.job.v1.ListJobsResponse\x12U\n" +
	"\x10ListArchivedJobs\x12\x1f.job.v1.ListArchivedJobsRequest\x1a .job.v1.ListArchivedJobsResponse\x12U\n" +
	"\x10RetryArchivedJob\x12\x1f.job.v1.RetryArchivedJobRequest\x1a .job.v1.RetryArchivedJobResponse\x12@\n" +
	"\tCancelJob\x12\x18.job.v1.CancelJobRequest\x1a\x19.job.v1.CancelJobResponse\x12C\n" +
	"\n" +
	"ListQueues\x12\x19.job.v1.ListQueuesRequest\x1a\x1a.job.v1.ListQueuesResponse\x12C\n" +
	"\n" +
	"PauseQueue\x12\x19.job.v1.PauseQueueRequest\x1a\x1a.job.v1.PauseQueueResponse\x12I\n" +
	"\fUnpauseQueue\x12\x1b.job.v1.UnpauseQueueRequest\x1a\x1c.job.v1.UnpauseQueueResponseBHZFgithub.com/PraneethaBabburi/Jobs-Processing-System/api/proto/jobv1;jobv1b\x06proto3"

var (
	file_api_proto_job_service_proto_rawDescOnce sync.Once
	file_api_proto_job_service_proto_rawDescData []byte
)

func file_api_proto_job_service_proto_rawDescGZIP() []byte {
	file_api_proto_job_service_proto_rawDescOnce.Do(func() {
		file_api_proto_job_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_job_service_proto_rawDesc), len(file_api_proto_job_service_proto_rawDesc)))
	})
	return file_api_proto_job_service_proto_rawDescData
}

var file_api_proto_job_service_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_proto_job_service_proto_goTypes = []any{
	(*SubmitJobRequest)(nil),         // 0: job.v1.SubmitJobRequest
	(*JobOptions)(nil),               // 1: job.v1.JobOptions
	(*SubmitJobResponse)(nil),        // 2: job.v1.SubmitJobResponse
	(*GetJobStatusRequest)(nil),      // 3: job.v1.GetJobStatusRequest
	(*GetJobStatusResponse)(nil),     // 4: job.v1.GetJobStatusResponse
	(*ListArchivedJobsRequest)(nil),  // 5: job.v1.ListArchivedJobsRequest
	(*ArchivedJobInfo)(nil),          // 6: job.v1.ArchivedJobInfo
	(*ListArchivedJobsResponse)(nil), // 7: job.v1.ListArchivedJobsResponse
	(*RetryArchivedJobRequest)(nil),  // 8: job.v1.RetryArchivedJobRequest
	(*RetryArchivedJobResponse)(nil), // 9: job.v1.RetryArchivedJobResponse
	(*ListJobsRequest)(nil),          // 10: job.v1.ListJobsRequest
	(*JobInfo)(nil),                  // 11: job.v1.JobInfo
	(*ListJobsResponse)(nil),         // 12: job.v1.ListJobsResponse
	(*CancelJobRequest)(nil),         // 13: job.v1.CancelJobRequest
	(*CancelJobResponse)(nil),        // 14: job.v1.CancelJobResponse
	(*ListQueuesRequest)(nil),        // 15: job.v1.ListQueuesRequest
	(*QueueInfo)(nil),                // 16: job.v1.QueueInfo
	(*ListQueuesResponse)(nil),       // 17: job.v1.ListQueuesResponse
	(*PauseQueueRequest)(nil),        // 18: job.v1.PauseQueueRequest
	(*PauseQueueResponse)(nil),       // 19: job.v1.PauseQueueResponse
	(*UnpauseQueueRequest)(nil),      // 20: job.v1.UnpauseQueueRequest
	(*UnpauseQueueResponse)(nil),     // 21: job.v1.UnpauseQueueResponse
}
var file_api_proto_job_service_proto_depIdxs = []int32{
	1,  // 0: job.v1.SubmitJobRequest.options:type_name -> job.v1.JobOptions
	6,  // 1: job.v1.ListArchivedJobsResponse.jobs:type_name -> job.v1.ArchivedJobInfo
	11, // 2: job.v1.ListJobsResponse.jobs:type_name -> job.v1.JobInfo
	16, // 3: job.v1.ListQueuesResponse.queues:type_name -> job.v1.QueueInfo
	0,  // 4: job.v1.JobService.SubmitJob:input_type -> job.v1.SubmitJobRequest
	3,  // 5: job.v1.JobService.GetJobStatus:input_type -> job.v1.GetJobStatusRequest
	10, // 6: job.v1.JobService.ListJobs:input_type -> job.v1.ListJobsRequest
	5,  // 7: job.v1.JobService.ListArchivedJobs:input_type -> job.v1.ListArchivedJobsRequest
	8,  // 8: job.v1.JobService.RetryArchivedJob:input_type -> job.v1.RetryArchivedJobRequest
	13, // 9: job.v1.JobService.CancelJob:input_type -> job.v1.CancelJobRequest
	15, // 10: job.v1.JobService.ListQueues:input_type -> job.v1.ListQueuesRequest
	18, // 11: job.v1.JobService.PauseQueue:input_type -> job.v1.PauseQueueRequest
	20, // 12: job.v1.JobService.UnpauseQueue:input_type -> job.v1.UnpauseQueueRequest
	2,  // 13: job.v1.JobService.SubmitJob:output_type -> job.v1.SubmitJobResponse
	4,  // 14: job.v1.JobService.GetJobStatus:output_type -> job.v1.GetJobStatusResponse
	12, // 15: job.v1.JobService.ListJobs:output_type -> job.v1.ListJobsResponse
	7,  // 16: job.v1.JobService.ListArchivedJobs:output_type -> job.v1.ListArchivedJobsResponse
	9,  // 17: job.v1.JobService.RetryArchivedJob:output_type -> job.v1.RetryArchivedJobResponse
	14, // 18: job.v1.JobService.CancelJob:output_type -> job.v1.CancelJobResponse
	17, // 19: job.v1.JobService.ListQueues:output_type -> job.v1.ListQueuesResponse
	19, // 20: job.v1.JobService.PauseQueue:output_type -> job.v1.PauseQueueResponse
	21, // 21: job.v1.JobService.UnpauseQueue:output_type -> job.v1.UnpauseQueueResponse
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_job_service_proto_init() }
func file_api_proto_job_service_proto_init() {
	if File_api_proto_job_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_job_service_proto_rawDesc), len(file_api_proto_job_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_job_service_proto_goTypes,
		DependencyIndexes: file_api_proto_job_service_proto_depIdxs,
		MessageInfos:      file_api_proto_job_service_proto_msgTypes,
	}.Build()
	File_api_proto_job_service_proto = out.File
	file_api_proto_job_service_proto_goTypes = nil
	file_api_proto_job_service_proto_depIdxs = nil
}
